# Generated by Django 4.2.2 on 2023-06-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('department', models.CharField(max_length=50)),
                ('schoolnumber', models.IntegerField()),
                ('classnumber', models.IntegerField()),
                ('furigana', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('addressnumber', models.CharField(max_length=50)),
                ('mobilenumber', models.CharField(max_length=50)),
                ('promotion', models.BooleanField()),
            ],
        ),
    ]
