# Generated by Django 4.2.2 on 2023-10-15 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='学年')),
                ('department', models.CharField(choices=[('AD', 'デザイン科'), ('EE', '電気工学科'), ('ME', '機械電子工学科'), ('CS', '情報工学科'), ('AC', '専攻科')], max_length=50, verbose_name='学科')),
                ('schoolnumber', models.CharField(max_length=10, verbose_name='学籍番号')),
                ('classnumber', models.IntegerField(verbose_name='クラス番号')),
                ('last_name_furigana', models.CharField(max_length=50, verbose_name='名字のふりがな')),
                ('first_name_furigana', models.CharField(max_length=50, verbose_name='名前のふりがな')),
                ('birthdate', models.DateField(verbose_name='生年月日')),
                ('age', models.IntegerField(verbose_name='年齢')),
                ('address', models.CharField(max_length=50, verbose_name='住所')),
                ('addressnumber', models.IntegerField(verbose_name='郵便番号')),
                ('mobilenumber', models.IntegerField(verbose_name='携帯電話番号')),
                ('promotion', models.BooleanField(verbose_name='条件付き進級者かどうか')),
                ('submitted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
