# Generated by Django 4.2.2 on 2023-10-13 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('department', models.CharField(choices=[('AD', 'デザイン科'), ('EE', '電気工学科'), ('ME', '機械電子工学科'), ('CS', '情報工学科'), ('AC', '専攻科')], max_length=50)),
                ('schoolnumber', models.CharField(max_length=10)),
                ('classnumber', models.IntegerField()),
                ('first_name_furigana', models.CharField(max_length=50)),
                ('last_name_furigana', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('addressnumber', models.IntegerField()),
                ('mobilenumber', models.IntegerField()),
                ('promotion', models.BooleanField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
