# Generated by Django 4.2.2 on 2023-10-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='求人番号')),
                ('name', models.CharField(max_length=100, verbose_name='会社名')),
                ('AD', models.IntegerField(blank=True, null=True)),
                ('EE', models.IntegerField(blank=True, null=True)),
                ('ME', models.IntegerField(blank=True, null=True)),
                ('CS', models.IntegerField(blank=True, null=True)),
                ('ALL', models.IntegerField(blank=True, null=True)),
                ('AC', models.IntegerField(blank=True, null=True)),
                ('prefecture', models.CharField(max_length=100, verbose_name='都道府県')),
                ('address', models.CharField(max_length=100, verbose_name='住所')),
                ('tel', models.CharField(max_length=100, verbose_name='電話番号')),
                ('PIC', models.CharField(max_length=100, verbose_name='担当')),
                ('workplace', models.CharField(max_length=100, verbose_name='勤務地')),
                ('qualified', models.CharField(max_length=100, verbose_name='推薦・自由')),
                ('method', models.CharField(max_length=100, verbose_name='応募方法')),
                ('selection_day', models.CharField(max_length=100, verbose_name='選考日')),
                ('naming', models.CharField(max_length=100, verbose_name='呼称')),
                ('money', models.CharField(max_length=100, verbose_name='資本金')),
                ('employee', models.CharField(max_length=100, verbose_name='従業員数')),
                ('type', models.CharField(max_length=100, verbose_name='業種')),
                ('detail', models.CharField(max_length=100, verbose_name='事業内容')),
                ('occupation', models.CharField(max_length=100, verbose_name='職種')),
                ('web', models.CharField(max_length=100, verbose_name='ホームページ')),
                ('mail', models.CharField(max_length=100, verbose_name='メールアドレス')),
                ('graduated', models.CharField(blank=True, max_length=100, null=True, verbose_name='既卒')),
                ('disabled', models.CharField(blank=True, max_length=100, null=True, verbose_name='障害者採用')),
                ('PDF', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name='日付')),
            ],
        ),
    ]
