# Generated by Django 4.2.2 on 2024-01-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='parent',
            field=models.BooleanField(default=False, verbose_name='保護者の了承'),
        ),
        migrations.AlterField(
            model_name='application',
            name='edicational_condition',
            field=models.BooleanField(blank=True, null=True, verbose_name='教務部条件'),
        ),
        migrations.AlterField(
            model_name='application',
            name='procedure_contract',
            field=models.BooleanField(blank=True, null=True, verbose_name='誓約書提出'),
        ),
        migrations.AlterField(
            model_name='application',
            name='procedure_pay',
            field=models.BooleanField(blank=True, null=True, verbose_name='認定試験料支払い'),
        ),
    ]
